#include <iostream>
#include <string>
#include "Vigenere.h"
#include "Kasiski.h"

using namespace std;

int main()
{
    //3.d Kasiski
    string TextoCifrado = "PBVRQVICADSKAÑSDETSJPSIEDBGGMPSLRPWRÑPWYEDSDEÑDRDPCRCPQMNPWKUBZVSFNVRDMTIPWUEQVVCBOVNUEDIFQLONMVNUVRSEIKAZYEACEYEDSETFPHLBHGUÑESOMEHLBXVAEEPUÑELISEUEFWHUNMCLPQPMBRRNBPVIÑMTIBVVEÑICANSJAMTJOKMDODSELPWIUFOZMQMVNFOHASESRJWRSFQCOTWVMBJGRPWVSUEXINQRSJEUEMGGRBDGNNILAGSJIDSVSUEEINTGRUEETFGGMPORDFOGTSSTOSEQOÑTGRRYVLPWJIFWXOTGGRPQRRJSKETXRNBLZETGGNEMUOTXJATORVJHRSFHVNUEJIBCHASEHEUEUOTIEFFGYATGGMPIKTBWUEÑENIEEU";
    string Prueba3 = "LNUDVMUYRMUDVLLPXAFZUEFAIOVWVMUOVMUEVMUEZCUDVSYWCIVCFGUCUNYCGALLGRCYTIJTRNNPJQOPJEMZITYLIAYYKRYEFDUDCAMAVRMZEAMBLEXPJCCQIEHPJTYXVNMLAEZTIMUOFRUFC";
    Kasiski K1(TextoCifrado);
    string claveK = K1.GetClave();
    cout << claveK << endl;
    string alfabetoD = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
    Vigenere emisorD(claveK, alfabetoD);
    cout << " Mensaje descifrado: " << emisorD.descifrar(TextoCifrado) << endl << endl;

    return 0;
}
